In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/05_model_input/downloaded_scenarios.csv")
df = df.loc[df["sector"] == "Power",:]

/var/folders/df/zghzv05d7xb8t9xy7y5ld_h40000gn/T/ipykernel_23570/3532604135.py:1: DtypeWarning: Columns (15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/05_model_input/downloaded_scenarios.csv")

# Compatible scenarios

In [19]:
# the EBITDA is likely to be negative when the values in fom_usd_per_mw_yr are higher
#  than capacity_factor * hours_per_year * scenario_price
incompatible_fixed_cost = df["om_cost_usd_per_mw_per_yr"] > df["scenario_capacity_factor"] * (24*365) * df["scenario_price"]

# the EBITDA is likely to be negative when fuel_price/efficiency > scenario_price .
incompatible_var_cost = df["fuel_price"] / df["efficiency_decimal"] > df["scenario_price"]

In [20]:
df = df.assign(
    incompatible_var_cost = incompatible_var_cost.astype(bool),
    incompatible_fixed_cost = incompatible_fixed_cost.astype(bool),
)

In [21]:
df.loc[df["scenario_type"] == "baseline", ["scenario_provider", "scenario"]].drop_duplicates()

        scenario_provider       scenario
368114          IMAGE 3.2  SSP1-baseline
399793          IMAGE 3.2  SSP2-baseline
1208657         WITCH 5.0      CO_CurPol
1349111         WITCH 5.0    EN_NoPolicy

In [25]:
pd.options.display.max_rows = 1000

incompatibility_flagged = df[[
    "scenario_provider", "scenario", "scenario_type", "scenario_geography","sector", "technology", 
    "incompatible_var_cost","incompatible_fixed_cost",
    "likely_incompatible_scenario","incompatible_scenario"]].drop_duplicates()


incompatibility_flagged = incompatibility_flagged.groupby(["scenario_provider", "scenario"]).agg(
    n_techs = ("technology", "nunique"),
    n_regions = ("scenario_geography", "nunique"),
    incompatible_var_cost = ("incompatible_var_cost", "any"),
    incompatible_fixed_cost = ("incompatible_fixed_cost", "any"),
)

incompatibility_flagged = incompatibility_flagged.assign(
    likely_incompatible_scenario = (incompatibility_flagged["incompatible_var_cost"] | incompatibility_flagged["incompatible_fixed_cost"]),
    incompatible_scenario = (incompatibility_flagged["incompatible_var_cost"] & incompatibility_flagged["incompatible_fixed_cost"]),
)


incompatibility_flagged.query("incompatible_fixed_cost == False")

                                                                        n_techs  \
scenario_provider     scenario
AIM/CGE 2.2           EN_NPi2020_1200f                                       14
                      EN_NPi2020_1400                                        14
                      EN_NPi2020_1400f                                       14
                      EN_NPi2020_1600                                        14
                      EN_NPi2020_1600f                                       14
                      EN_NPi2020_1800                                        14
                      EN_NPi2020_1800f                                       14
AIM/CGE-Korea 2.1     CO_2Deg2020                                            11
                      CO_2Deg2030                                            11
                      CO_BAU                                                  8
                      CO_CurPol                                               8
                      CO_GPP                                                 11
                      CO_NDCMCS                                              11
AIM/Hub-Japan 2.1     EN_NP_2025_-1002050                                    11
                      EN_NP_2025_-302050                                     10
                      EN_NP_2025_-402050                                     10
                      EN_NP_2025_-502050                                     11
                      EN_NP_2025_-602050                                     11
                      EN_NP_2025_-702050                                     11
                      EN_NP_2025_-802050                                     11
                      EN_NP_2025_-902050                                     11
                      EN_NP_CurPol                                            8
                      EN_NP_UNDC                                             10
AIM/Hub-Korea 2.0     EN_NP_2025_-1002050                                    11
                      EN_NP_2025_-302050                                      8
                      EN_NP_2025_-402050                                      9
                      EN_NP_2025_-502050                                     11
                      EN_NP_2025_-602050                                     11
                      EN_NP_2025_-702050                                     10
                      EN_NP_2025_-802050                                     11
                      EN_NP_2025_-902050                                     10
                      EN_NP_CurPol                                            8
                      EN_NP_UNDC                                             10
EPPA 6                2CNow_Gradual                                           7
                      Paris1.5C_OptTax                                        7
                      Paris2C_Gradual                                         7
                      Paris2C_OptTax                                          7
                      ParisFlat                                               7
                      ParisForever                                            7
                      Ref                                                     7
GCAM 5.2              NGFS1_Current policies (Hot house world, Rep)           6
                      NGFS1_Immediate 2C with CDR (Orderly, Rep)              9
GCAM 5.3              NGFS2_Below 2°C                                        12
                      NGFS2_Current Policies                                 12
                      NGFS2_Divergent Net Zero Policies                      12
                      NGFS2_Nationally Determined Contributions (NDCs)       12
                      NGFS2_Net-Zero 2050                                    12
                      R_BAU                                                   6
                      R_MAC_30_n0                                             9
                      R_MAC_35_n0                                             9
                      R_MAC_35_n8                                             9
                      R_MAC_40_n0                                             9
                      R_MAC_40_n8                                             9
                      R_MAC_45_n0                                             9
                      R_MAC_45_n8                                             9
                      R_MAC_50_n0                                             9
                      R_MAC_50_n8                                             9
                      R_MAC_55_n0                                             9
                      R_MAC_55_n8                                             9
                      R_MAC_60_n0                                             9
                      R_MAC_60_n8                                             9
                      R_MAC_65_n0                                             9
                      R_MAC_65_n8                                             9
                      R_MAC_70_n0                                             9
                      R_MAC_70_n8                                             9
                      R_MAC_75_n0                                             9
                      R_MAC_75_n8                                             9
                      R_MAC_80_n0                                             9
                      R_MAC_80_n8                                             9
                      R_MAC_85_n0                                             9
                      R_MAC_85_n8                                             9
                      R_MAC_90_n0                                             9
                      R_MAC_90_n8                                             9
                      R_MAC_95_n0                                             9
                      R_MAC_95_n8                                             9
                      R_MAC_99_n0                                             9
                      R_MAC_99_n8                                             9
                      SSP_SSP2                                                9
                      SSP_SSP3                                                9
                      SSP_SSP4                                                9
                      SSP_SSP5                                                9
GCAM-PR 5.3           PR_CP_PriceOnly                                        12
                      PR_NDC_PriceOnly                                       12
                      PR_baseline                                             9
MESSAGEix-GLOBIOM_1.2 COV_GreenPush                                           3
                      COV_GreenPush_max_GDP                                   3
                      COV_GreenPush_min_GDP                                   3
                      COV_NoPolicyNoCOVID_550                                 3
                      COV_Restore                                             3
                      COV_SelfReliance                                        3
                      COV_SelfReliance_max_GDP                                3
                      COV_SelfReliance_min_GDP                                3
                      COV_SmartUse                                            3
WITCH 4.6             DISCRATE_Ref_dr2p                                      11
                      DISCRATE_Ref_dr3p                                      11
                      DISCRATE_Ref_dr4p                                      11
                      DISCRATE_Ref_dr5p                                      11

                                                                        n_regions  \
scenario_provider     scenario
AIM/CGE 2.2           EN_NPi2020_1200f                                         18
                      EN_NPi2020_1400                                          18
                      EN_NPi2020_1400f                                         18
                      EN_NPi2020_1600                                          18
                      EN_NPi2020_1600f                                         18
                      EN_NPi2020_1800                                          18
                      EN_NPi2020_1800f                                         18
AIM/CGE-Korea 2.1     CO_2Deg2020                                               2
                      CO_2Deg2030                                               2
                      CO_BAU                                                    2
                      CO_CurPol                                                 2
                      CO_GPP                                                    2
                      CO_NDCMCS                                                 2
AIM/Hub-Japan 2.1     EN_NP_2025_-1002050                                       2
                      EN_NP_2025_-302050                                        2
                      EN_NP_2025_-402050                                        2
                      EN_NP_2025_-502050                                        2
                      EN_NP_2025_-602050                                        2
                      EN_NP_2025_-702050                                        2
                      EN_NP_2025_-802050                                        2
                      EN_NP_2025_-902050                                        2
                      EN_NP_CurPol                                              2
                      EN_NP_UNDC                                                2
AIM/Hub-Korea 2.0     EN_NP_2025_-1002050                                       2
                      EN_NP_2025_-302050                                        2
                      EN_NP_2025_-402050                                        2
                      EN_NP_2025_-502050                                        2
                      EN_NP_2025_-602050                                        2
                      EN_NP_2025_-702050                                        2
                      EN_NP_2025_-802050                                        2
                      EN_NP_2025_-902050                                        2
                      EN_NP_CurPol                                              2
                      EN_NP_UNDC                                                2
EPPA 6                2CNow_Gradual                                            13
                      Paris1.5C_OptTax                                         13
                      Paris2C_Gradual                                          13
                      Paris2C_OptTax                                           13
                      ParisFlat                                                13
                      ParisForever                                             13
                      Ref                                                      13
GCAM 5.2              NGFS1_Current policies (Hot house world, Rep)            26
                      NGFS1_Immediate 2C with CDR (Orderly, Rep)               26
GCAM 5.3              NGFS2_Below 2°C                                          27
                      NGFS2_Current Policies                                   27
                      NGFS2_Divergent Net Zero Policies                        27
                      NGFS2_Nationally Determined Contributions (NDCs)         27
                      NGFS2_Net-Zero 2050                                      27
                      R_BAU                                                    27
                      R_MAC_30_n0                                              27
                      R_MAC_35_n0                                              27
                      R_MAC_35_n8                                              27
                      R_MAC_40_n0                                              27
                      R_MAC_40_n8                                              27
                      R_MAC_45_n0                                              27
                      R_MAC_45_n8                                              27
                      R_MAC_50_n0                                              27
                      R_MAC_50_n8                                              27
                      R_MAC_55_n0                                              27
                      R_MAC_55_n8                                              27
                      R_MAC_60_n0                                              27
                      R_MAC_60_n8                                              27
                      R_MAC_65_n0                                              27
                      R_MAC_65_n8                                              27
                      R_MAC_70_n0                                              27
                      R_MAC_70_n8                                              27
                      R_MAC_75_n0                                              27
                      R_MAC_75_n8                                              27
                      R_MAC_80_n0                                              27
                      R_MAC_80_n8                                              27
                      R_MAC_85_n0                                              27
                      R_MAC_85_n8                                              27
                      R_MAC_90_n0                                              27
                      R_MAC_90_n8                                              27
                      R_MAC_95_n0                                              27
                      R_MAC_95_n8                                              27
                      R_MAC_99_n0                                              27
                      R_MAC_99_n8                                              27
                      SSP_SSP2                                                 27
                      SSP_SSP3                                                 27
                      SSP_SSP4                                                 27
                      SSP_SSP5                                                 27
GCAM-PR 5.3           PR_CP_PriceOnly                                          11
                      PR_NDC_PriceOnly                                         11
                      PR_baseline                                              11
MESSAGEix-GLOBIOM_1.2 COV_GreenPush                                            14
                      COV_GreenPush_max_GDP                                    14
                      COV_GreenPush_min_GDP                                    14
                      COV_NoPolicyNoCOVID_550                                  14
                      COV_Restore                                              14
                      COV_SelfReliance                                         14
                      COV_SelfReliance_max_GDP                                 14
                      COV_SelfReliance_min_GDP                                 14
                      COV_SmartUse                                             14
WITCH 4.6             DISCRATE_Ref_dr2p                                        15
                      DISCRATE_Ref_dr3p                                        15
                      DISCRATE_Ref_dr4p                                        15
                      DISCRATE_Ref_dr5p                                        15

                                                                        incompatible_var_cost  \
scenario_provider     scenario
AIM/CGE 2.2           EN_NPi2020_1200f                                                   True
                      EN_NPi2020_1400                                                    True
                      EN_NPi2020_1400f                                                   True
                      EN_NPi2020_1600                                                    True
                      EN_NPi2020_1600f                                                   True
                      EN_NPi2020_1800                                                    True
                      EN_NPi2020_1800f                                                   True
AIM/CGE-Korea 2.1     CO_2Deg2020                                                       False
                      CO_2Deg2030                                                       False
                      CO_BAU                                                            False
                      CO_CurPol                                                         False
                      CO_GPP                                                            False
                      CO_NDCMCS                                                         False
AIM/Hub-Japan 2.1     EN_NP_2025_-1002050                                               False
                      EN_NP_2025_-302050                                                False
                      EN_NP_2025_-402050                                                False
                      EN_NP_2025_-502050                                                False
                      EN_NP_2025_-602050                                                False
                      EN_NP_2025_-702050                                                False
                      EN_NP_2025_-802050                                                False
                      EN_NP_2025_-902050                                                False
                      EN_NP_CurPol                                                      False
                      EN_NP_UNDC                                                        False
AIM/Hub-Korea 2.0     EN_NP_2025_-1002050                                               False
                      EN_NP_2025_-302050                                                False
                      EN_NP_2025_-402050                                                False
                      EN_NP_2025_-502050                                                False
                      EN_NP_2025_-602050                                                False
                      EN_NP_2025_-702050                                                False
                      EN_NP_2025_-802050                                                False
                      EN_NP_2025_-902050                                                False
                      EN_NP_CurPol                                                      False
                      EN_NP_UNDC                                                        False
EPPA 6                2CNow_Gradual                                                     False
                      Paris1.5C_OptTax                                                  False
                      Paris2C_Gradual                                                   False
                      Paris2C_OptTax                                                    False
                      ParisFlat                                                         False
                      ParisForever                                                      False
                      Ref                                                               False
GCAM 5.2              NGFS1_Current policies (Hot house world, Rep)                     False

In [27]:
df.loc[df["scenario_provider"] == "WITCH 4.6", "scenario"].unique()

array(['DISCRATE_Ref_dr2p', 'DISCRATE_Ref_dr3p', 'DISCRATE_Ref_dr4p',
       'DISCRATE_Ref_dr5p'], dtype=object)