In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/05_model_input/downloaded_scenarios.csv")
df = df.loc[df["sector"] == "Power",:]

/var/folders/df/zghzv05d7xb8t9xy7y5ld_h40000gn/T/ipykernel_23570/3532604135.py:1: DtypeWarning: Columns (15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/05_model_input/downloaded_scenarios.csv")

# Compatible scenarios

In [19]:
# the EBITDA is likely to be negative when the values in fom_usd_per_mw_yr are higher
#  than capacity_factor * hours_per_year * scenario_price
incompatible_fixed_cost = df["om_cost_usd_per_mw_per_yr"] > df["scenario_capacity_factor"] * (24*365) * df["scenario_price"]

# the EBITDA is likely to be negative when fuel_price/efficiency > scenario_price .
incompatible_var_cost = df["fuel_price"] / df["efficiency_decimal"] > df["scenario_price"]

In [20]:
df = df.assign(
    incompatible_var_cost = incompatible_var_cost.astype(bool),
    incompatible_fixed_cost = incompatible_fixed_cost.astype(bool),
)

In [21]:
df.loc[df["scenario_type"] == "baseline", ["scenario_provider", "scenario"]].drop_duplicates()

        scenario_provider       scenario
368114          IMAGE 3.2  SSP1-baseline
399793          IMAGE 3.2  SSP2-baseline
1208657         WITCH 5.0      CO_CurPol
1349111         WITCH 5.0    EN_NoPolicy

In [31]:
pd.options.display.max_rows = 1000

incompatibility_flagged = df[[
    "scenario_provider", "scenario", "scenario_type","sector", "technology", #, "scenario_geography"
    "incompatible_var_cost","incompatible_fixed_cost",
    "likely_incompatible_scenario","incompatible_scenario"]].drop_duplicates()


incompatibility_flagged = incompatibility_flagged.groupby(["scenario_provider", "scenario"]).agg(
    n_techs = ("technology", "nunique"),
    # n_regions = ("scenario_geography", "nunique"),
    incompatible_var_cost = ("incompatible_var_cost", "sum"),
    incompatible_fixed_cost = ("incompatible_fixed_cost", "sum"),
)

incompatibility_flagged = incompatibility_flagged.assign(
    likely_incompatible_scenario = (incompatibility_flagged["incompatible_var_cost"] | incompatibility_flagged["incompatible_fixed_cost"]),
    incompatible_scenario = (incompatibility_flagged["incompatible_var_cost"] & incompatibility_flagged["incompatible_fixed_cost"]),
)


incompatibility_flagged.query("incompatible_fixed_cost < 8")

                                                                            n_techs  \
scenario_provider         scenario
AIM/CGE 2.2               EN_INDCi2030_1000f                                     14
                          EN_INDCi2030_1200                                      14
                          EN_INDCi2030_1200f                                     14
                          EN_INDCi2030_1400                                      14
                          EN_INDCi2030_1400f                                     14
                          EN_INDCi2030_1600                                      14
                          EN_INDCi2030_1600f                                     14
                          EN_INDCi2030_1800                                      14
                          EN_INDCi2030_1800f                                     14
                          EN_INDCi2030_800f                                      14
                          EN_INDCi2030_900f                                      14
                          EN_INDCi2100                                           14
                          EN_NPi2020_1000                                        14
                          EN_NPi2020_1000f                                       14
                          EN_NPi2020_1200                                        14
                          EN_NPi2020_1200f                                       14
                          EN_NPi2020_1400                                        14
                          EN_NPi2020_1400f                                       14
                          EN_NPi2020_1600                                        14
                          EN_NPi2020_1600f                                       14
                          EN_NPi2020_1800                                        14
                          EN_NPi2020_1800f                                       14
                          EN_NPi2020_300f                                        14
                          EN_NPi2020_400f                                        14
                          EN_NPi2020_500f                                        14
                          EN_NPi2020_600                                         14
                          EN_NPi2020_600f                                        14
                          EN_NPi2020_700                                         14
                          EN_NPi2020_700f                                        14
                          EN_NPi2020_800                                         14
                          EN_NPi2020_800f                                        14
                          EN_NPi2020_900                                         14
                          EN_NPi2020_900f                                        14
                          EN_NPi2100                                             11
AIM/CGE-Korea 2.1         CO_2Deg2020                                            11
                          CO_2Deg2030                                            11
                          CO_BAU                                                  8
                          CO_Bridge                                              11
                          CO_CurPol                                               8
                          CO_GPP                                                 11
                          CO_NDCMCS                                              11
AIM/Enduse-Japan 2.1      EN_NP_2025_-1002050                                     9
                          EN_NP_2025_-502050                                      8
                          EN_NP_2025_-602050                                      9
                          EN_NP_2025_-702050                                      9
                          EN_NP_2025_-802050                                      9
                          EN_NP_2025_-902050                                      9
                          EN_NP_BL                                                8
                          EN_NP_CurPol                                            9
                          EN_NP_UNDC                                              8
AIM/Hub-Japan 2.1         EN_NP_2025_-1002050                                    11
                          EN_NP_2025_-302050                                     10
                          EN_NP_2025_-402050                                     10
                          EN_NP_2025_-502050                                     11
                          EN_NP_2025_-602050                                     11
                          EN_NP_2025_-702050                                     11
                          EN_NP_2025_-802050                                     11
                          EN_NP_2025_-902050                                     11
                          EN_NP_CurPol                                            8
                          EN_NP_UNDC                                             10
AIM/Hub-Korea 2.0         EN_NP_2025_-1002050                                    11
                          EN_NP_2025_-302050                                      8
                          EN_NP_2025_-402050                                      9
                          EN_NP_2025_-502050                                     11
                          EN_NP_2025_-602050                                     11
                          EN_NP_2025_-702050                                     10
                          EN_NP_2025_-802050                                     11
                          EN_NP_2025_-902050                                     10
                          EN_NP_CurPol                                            8
                          EN_NP_UNDC                                             10
COFFEE 1.1                CO_2Deg2020                                             9
                          CO_2Deg2030                                             9
                          CO_BAU                                                  9
                          CO_Bridge                                               9
                          CO_CurPol                                               9
                          CO_GPP                                                  9
                          CO_NDCplus                                              9
                          EN_INDCi2030_1000                                       9
                          EN_INDCi2030_1000_NDCp                                  9
                          EN_INDCi2030_1000f                                      9
                          EN_INDCi2030_1200                                       9
                          EN_INDCi2030_1200f                                      9
                          EN_INDCi2030_1400                                       9
                          EN_INDCi2030_1400f                                      9
                          EN_INDCi2030_1600                                       9
                          EN_INDCi2030_1600f                                      9
                          EN_INDCi2030_1800                                       9
                          EN_INDCi2030_1800f                                      9
                          EN_INDCi2030_2000                                       9
                          EN_INDCi2030_2000f                                      9
                          EN_INDCi2030_2500                                       9
                          EN_INDCi2030_2500f                                      9
                          EN_INDCi2030_400f                                       9
                          EN_INDCi2030_500                                        9
                          EN_INDCi2030_500f                                       9
                          EN_INDCi2030_600                                        9
                          EN_INDCi2030_600_NDCp                                   9
                          EN_INDCi2030_600f                                       9
                          EN_INDCi2030_700                                        9
                          EN_INDCi2030_700f                                       9
                          EN_INDCi2030_800                                        9
                          EN_INDCi2030_800f                                       9
                          EN_INDCi2030_900                                        9
                          EN_INDCi2030_900f                                       9
                          EN_INDCi2100                                            9
                          EN_INDCi2100_COV_NDCp                                   9
                          EN_NPi2020_1000                                         9
                          EN_NPi2020_1000f                                        9
                          EN_NPi2020_1200                                         9
                          EN_NPi2020_1200f                                        9
                          EN_NPi2020_1400                                         9
                          EN_NPi2020_1400f                                        9
                          EN_NPi2020_1600                                         9
                          EN_NPi2020_1600f                                        9
                          EN_NPi2020_1800                                         9
                          EN_NPi2020_1800f                                        9
                          EN_NPi2020_2000                                         9
                          EN_NPi2020_2000f                                        9
                          EN_NPi2020_2500                                         9
                          EN_NPi2020_2500f                                        9
                          EN_NPi2020_400f                                         9
                          EN_NPi2020_400f_lowBECCS                                9
                          EN_NPi2020_500                                          9
                          EN_NPi2020_500f                                         9
                          EN_NPi2020_600                                          9
                          EN_NPi2020_600f                                         9
                          EN_NPi2020_700                                          9
                          EN_NPi2020_700f                                         9
                          EN_NPi2020_800                                          9
                          EN_NPi2020_800f                                         9
                          EN_NPi2020_900                                          9
                          EN_NPi2020_900f                                         9
                          EN_NPi2100                                              9
EPPA 6                    2CNow_Gradual                                           7
                          Paris1.5C_OptTax                                        7
                          Paris2C_Gradual                                         7
                          Paris2C_OptTax                                          7
                          ParisFlat                                               7
                          ParisForever                                            7
                          Ref                                                     7
GCAM 5.2                  NGFS1_Current policies (Hot house world, Rep)           6
                          NGFS1_Immediate 2C with CDR (Orderly, Rep)              9
GCAM 5.3                  NGFS2_Below 2°C                                        12
                          NGFS2_Current Policies                                 12
                          NGFS2_Delayed Transition                               12
                          NGFS2_Divergent Net Zero Policies                      12
                          NGFS2_Nationally Determined Contributions (NDCs)       12
                          NGFS2_Net-Zero 2050                                    12
                          R_BAU                                                   6
                          R_MAC_30_n0                                             9
                          R_MAC_35_n0                                             9
                          R_MAC_35_n8                                             9
                          R_MAC_40_n0                                             9
                          R_MAC_40_n8                                             9
                          R_MAC_45_n0                                             9
                          R_MAC_45_n8                                             9
                          R_MAC_50_n0                                             9
                          R_MAC_50_n8                                             9
                          R_MAC_55_n0                                             9
                          R_MAC_55_n8                                             9
                          R_MAC_60_n0                                             9
                          R_MAC_60_n8                                             9
                          R_MAC_65_n0                                             9
                          R_MAC_65_n8                                             9
                          R_MAC_70_n0                                             9
                          R_MAC_70_n8                                             9
                          R_MAC_75_n0                                             9
                          R_MAC_75_n8                                             9
                          R_MAC_80_n0                                             9
                          R_MAC_80_n8                                             9
                          R_MAC_85_n0                                             9
                          R_MAC_85_n8                                             9
                          R_MAC_90_n0                                             9
                          R_MAC_90_n8                                             9
                          R_MAC_95_n0                                             9
                          R_MAC_95_n8                                             9
                          R_MAC_99_n0                                             9
                          R_MAC_99_n8                                             9
                          SSP_SSP2                                                9
                          SSP_SSP3                                                9
                          SSP_SSP4                                                9
                          SSP_SSP5                                                9
GCAM-PR 5.3               PR_CP_PriceOnly                                        12
                          PR_NDC_PriceOnly                                       12
                          PR_baseline                                             9
GEM-E3_V2021              EN_INDCi2030_1000                                       9
                          EN_INDCi2030_1000_COV                                   9
                          EN_INDCi2030_1000_COV_NDCp                              9
                          EN_INDCi2030_1000_NDCp                                  9
                          EN_INDCi2030_1000f                                      9
                          EN_INDCi2030_1000f_COV                                  9
                          EN_INDCi2030_1000f_COV_NDCp                             9
                          EN_INDCi2030_1000f_NDCp                                 9
                          EN_INDCi2030_1400                                       9
                          EN_INDCi2030_1400f                                      9
                          EN_INDCi2030_1800                                       9
                          EN_INDCi2030_1800f                                      9
                          EN_INDCi2030_600f                                       9
                          EN_INDCi2030_600f_COV                                   9
                          EN_INDCi2030_600f_COV_NDCp                              9
                          EN_INDCi2030_600f_NDCp                                  9
                          EN_INDCi2030_800                                        9
                          EN_INDCi2030_800f                                       9
                          EN_INDCi2100                                            9
                          EN_INDCi2100_COV                                        9
                          EN_INDCi2100_COV_NDCp                                   9
                          EN_INDCi2100_NDCp                                       9
                          EN_NPi2020_1000                                         9
                          EN_NPi2020_1000_COV                                     9
                          EN_NPi2020_1000f                                        9
                          EN_NPi2020_1000f_COV                                    9
                          EN_NPi2020_1400                                         9
                          EN_NPi2020_1400f                                        9
                          EN_NPi2020_1800                                         9
                          EN_NPi2020_1800f                                        9
                          EN_NPi2020_400f                                         9
                          EN_NPi2020_500                                          9
                          EN_NPi2020_500f                                         9
                          EN_NPi2020_600                                          9
                          EN_NPi2020_600_COV                                      9
                          EN_NPi2020_600f                                         9
                          EN_NPi2020_600f_COV                                     9
                          EN_NPi2020_800                                          9
                          EN_NPi2020_800f                                         9
                          EN_NPi2100                                              9
                          EN_NPi2100_COV                                          9
IMACLIM 1.1               ADVANCE_2020_1.5C-2100_WP6                             10
                          ADVANCE_2020_Med2C_WP6                                 10
                          ADVANCE_2020_WB2C_WP6                                  10
                          ADVANCE_2030_Med2C_WP6                                 10
                          ADVANCE_2030_Price1.5C_WP6                             10
                          ADVANCE_2030_WB2C_WP6                                  10
                          ADVANCE_INDC_WP6                                       10
                          ADVANCE_NoPolicy_WP6                                   10
                          ADVANCE_Reference_WP6                                  10
                          SSP1_NoPolicy_TranspBase                               10

In [27]:
df.loc[df["scenario_provider"] == "WITCH 4.6", "scenario"].unique()

array(['DISCRATE_Ref_dr2p', 'DISCRATE_Ref_dr3p', 'DISCRATE_Ref_dr4p',
       'DISCRATE_Ref_dr5p'], dtype=object)